// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDymL_jcoAQF0JVfiMlIgjh-QkJ1_TFLig',
    appId: '1:345851825256:web:1ae129cdb8b75dff3c7fdd',
    messagingSenderId: '345851825256',
    projectId: 'fluttertp-ef72e',
    authDomain: 'fluttertp-ef72e.firebaseapp.com',
    storageBucket: 'fluttertp-ef72e.firebasestorage.app',
    measurementId: 'G-CVYV608S0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQ0Ef4gMQ5jtdmJwbG9ZefVQafbMVIWY',
    appId: '1:345851825256:android:7f47be5fa11b70033c7fdd',
    messagingSenderId: '345851825256',
    projectId: 'fluttertp-ef72e',
    storageBucket: 'fluttertp-ef72e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNk2mIjowiRPOvdmEdmFsWprd3sa59efM',
    appId: '1:345851825256:ios:988bc4cd158997df3c7fdd',
    messagingSenderId: '345851825256',
    projectId: 'fluttertp-ef72e',
    storageBucket: 'fluttertp-ef72e.firebasestorage.app',
    iosBundleId: 'com.example.fluttertp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNk2mIjowiRPOvdmEdmFsWprd3sa59efM',
    appId: '1:345851825256:ios:988bc4cd158997df3c7fdd',
    messagingSenderId: '345851825256',
    projectId: 'fluttertp-ef72e',
    storageBucket: 'fluttertp-ef72e.firebasestorage.app',
    iosBundleId: 'com.example.fluttertp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDymL_jcoAQF0JVfiMlIgjh-QkJ1_TFLig',
    appId: '1:345851825256:web:373e798a55ac75ba3c7fdd',
    messagingSenderId: '345851825256',
    projectId: 'fluttertp-ef72e',
    authDomain: 'fluttertp-ef72e.firebaseapp.com',
    storageBucket: 'fluttertp-ef72e.firebasestorage.app',
    measurementId: 'G-RDVC22YXBX',
  );
}
